skwibl script modified, favicon changed

diff --git a/skwibl b/skwibl
--- a/skwibl
+++ b/skwibl
@@ -2,10 +2,10 @@
 
 
 ## dynamic server
-DYN='app.coffee'
+DYN='app'
 
 ## socket server
-SOC='server.coffee'
+SOC='server'
 
 ## coffee executable
 COFFEE='node_modules/coffee-script/bin/coffee'
@@ -38,13 +38,13 @@ PASSWORD='fuThoh5eipe8'
 TMP_TEMPLATE='~'
 
 ## node execution command
-NODE_CMD='node u-nouse-idle-notification --expose-gc'
+NODE_CMD='node --nouse-idle-notification --expose-gc'
 
 ## coffee execution command
 COFFEE_OPT='--nodejs "--nouse-idle-notification --expose-gc"'
 
 ## node debug command for dynamic server
-DEBUG_CMD='node --debug $DYN & node-inspector &'
+DEBUG_CMD="node --debug $DYN.js & node-inspector &"
 
 ## redis flush command
 FLUSH_REDIS_CMD='redis-cli flushall'
@@ -130,19 +130,19 @@ function reset {
 ## start dynamic server
 function startDyn {
   echo "starting dynamic"
-  eval "$COFFEE $DYN $COFFEE_OPT"
+  eval "$COFFEE $DYN.coffee $COFFEE_OPT"
 }
 
 ## start socket server
 function startSocket {
   echo "starting sockets"
-  eval "$COFFEE $SOC $COFFEE_OPT"
+  eval "$COFFEE $SOC.coffee $COFFEE_OPT"
 }
 
 ## run in production procedure
 function product {
   echo "production starting"
-  eval "NODE_ENV=production $NODE_CMD $DYN & NODE_ENV=production  $NODE_CMD $SOC"
+  eval "NODE_ENV=production $NODE_CMD $DYN.js & NODE_ENV=production  $NODE_CMD $SOC.js"
 }
 
 ## deploy procedure
@@ -169,64 +169,55 @@ function update {
   patch
 }
 
-## options check and parse
-##if ! options=$(getopt -o abcdeiprsuh: -l dynamic,build,clean,deploy,debug,init,product,reset,socket,update,help -- "$@"); then
-##  exit 1
-##fi
-
-##set -- $options
-
-##while [ $# -gt 0 ]; do
-  case "$1" in
-    -a|--dynamic)
-      init
-      build
-      startDyn
-      exit 0;;
-    -b|--build)
-      build
-      exit 0;;
-    -c|--clean)
+case "$1" in
+  -a|--dynamic)
+    init
+    build
+    startDyn
+    exit 0;;
+  -b|--build)
+    build
+    exit 0;;
+  -c|--clean)
+    clean
+    exit 0;;
+  -d|--deploy)
+    clean
+    init
+    build
+    deploy
+    exit 0;;
+  -e|--debug)
+    init
+    build
+    debug;;
+  -i|--init)
+    init
+    exit 0;;
+  -p|--product)
+    init
+    build
+    product;;
+  -r|--reset)
+    read -p "You are going to reset project files and flush db. Do you want to continue (y/n)?" REPLY
+    if [ $REPLY == 'y' ]; then
       clean
-      exit 0;;
-    -d|--deploy)
-      clean
-      init
-      build
-      deploy
-      exit 0;;
-    -e|--debug)
-      init
-      build
-      debug;;
-    -i|--init)
-      init
-      exit 0;;
-    -p|--product)
-      init
-      build
-      product;;
-    -r|--reset)
-      read -p "You are going to reset project files and flush db. Do you want to continue (y/n)?" REPLY
-      if [ $REPLY == 'y' ]; then
-        clean
-        reset
-      fi
-      exit 0;;
-    -s|--socket)
-      startSocket
-      exit 0;;
-    -u|--update)
-      update
-      exit 0;;
-    -h|--help)
-      echo -e $USAGE
-      exit 0;;
-    "?")
-      echo "Invalid option $OPTARG. Try $0 -h for help"
-      exit 1;;
-    *)
-      echo "Unknown error while processing options"
-      exit 1;;
-  esac
-##done
+      reset
+    fi
+    exit 0;;
+  -s|--socket)
+    startSocket
+    exit 0;;
+  -u|--update)
+    update
+    exit 0;;
+  -h|--help)
+    echo -e $USAGE
+    exit 0;;
+  "?")
+    echo "Invalid option $OPTARG. Try $0 -h for help"
+    exit 1;;
+  *)
+    echo "Unknown error while processing options"
+    exit 1;;
+esac
